apiVersion: 1

datasources:
  - name: grafana-postgresql-datasource
    type: grafana-postgresql-datasource
    access: proxy
    url: db:5432
    user: ${POSTGRES_READ_USER}
    database: ""
    basicAuth: false
    isDefault: true
    jsonData:
      connMaxLifetime: 14400
      database: logs_db
      maxIdleConns: 100
      maxIdleConnsAuto: true
      maxOpenConns: 100
      postgresVersion: 1500
      sslmode: "disable"
    secureJsonData:
      password: ${POSTGRES_READ_PASSWORD}
